[package]
name = "kitchen-sink-demo"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }
topcoat = { git = "https://github.com/petehunt/topcoat.git", rev = "0fef963aa8f7dfec8e4ab20af1a3152cb6e2beb8", features = ["htmx", "tailwind", "vercel"] }

[build-dependencies]
topcoat = { git = "https://github.com/petehunt/topcoat.git", rev = "0fef963aa8f7dfec8e4ab20af1a3152cb6e2beb8", default-features = false, features = ["tailwind"] }

[[bin]]
name = "kitchen-sink-demo"
path = "src/main.rs"

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
